version: '3.9'
services:
  app:
    container_name: golang-hexagonal-archithecture-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
    tty: true  
    depends_on:
      - mysql-db 
  mysql-db:
    image: 'mysql:8.0.25'
    container_name: golang-hexagonal-archithecture-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - '3306:3306'
    tty: true
      
