version: '3.9'
services:
  app:
    container_name: golang-hexagonal-archithecture-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
    tty: true  
    depends_on:
      - db 
  db:
    image: 'mysql:8.0.25'
    command: --default-authentication-plugin=mysql_native_password
    container_name: golang-hexagonal-archithecture-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: banking
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: banking
    ports:
      - '3306:3306'
    tty: true
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        
